# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d03ba2517f4ece9dea624f43df41f68597f6f6bab4595801adf38957ba21aa62699074df6eef9c57d6c31108a64ffa6a3dc19ea6459ead96f8b326cf3dddcc

test:
  secret_key_base: 73ab02ec6627eeee92d8480d4e09dfda4b273a5fd299d776750118c551108289a59edb3fe920e2c964819fcc877ff1c9d3aa75c003028f4fa196b492ef9cf19a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
